### ISSUE TITLE
Use Service Principal secrets instead of SAS token

### ISSUE THREAD

**Issue by kforeverisback** [jak119/hassio-backup-azure-blob#66]
First of all, thanks a ton for the Addon!! Awesome work!

For long term usability, I'd like to use a service principal and client secret to authenticate `azcopy`.

Currently the SAS token generator only supports SAS token validity upto 7 days.

Also, using Azure Active Directory (Service Principal) is recommended over SAS token in general.

### Possible Implementation:

```yaml
# config.yaml
tenant_id: [TENANT-ID]
storage_url: https://[account].blob.core.windows.net/[container]/[path/to/virtual/dir]
principal_id: [PRINCIPAL-ID]
client_secret: [!secret]
delete: false
```

According to `azcopy login` [documentation:](https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-login?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json#examples) we can use the cmd below to login with service principal and secret:

```bash
# Export AZCOPY_SPA_CLIENT_SECRET with the secret, then run
azcopy login --service-principal --application-id <your service principal's application ID>
```
